apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

resources:
  - https://github.com/redhat-na-ssa/demo-ai-gitops-catalog/components/operators/gpu-operator-certified/instance/overlays/time-sliced?ref=v0.16
  - https://github.com/redhat-na-ssa/demo-ai-gitops-catalog/components/operators/gpu-operator-certified/operator/overlays/stable?ref=v0.16
