apiVersion: apps/v1
kind: Deployment
metadata:
  name: whisper-tiny
  labels:
    app: whisper-tiny
spec:
  replicas: 1
  selector:
    matchLabels:
      app: whisper-tiny
  template:
    metadata:
      labels:
        app: whisper-tiny
        runai/queue: test
      annotations:
        gpu-fraction: "0.5"
    spec:
      schedulerName: kai-scheduler
      tolerations:
      - effect: NoSchedule
        key: nvidia.com/gpu
      # vLLM needs to access the host's shared memory for tensor parallel inference.
      volumes:
      - name: shm
        emptyDir:
          medium: Memory
          sizeLimit: "2Gi"
      containers:
      - name: whisper-tiny
        image: vllm/vllm-openai:latest # must be v0.7.3 or later
        command: ["/bin/sh", "-c"]
        args: [
          "vllm serve openai/whisper-tiny --task transcription"
        ]
        ports:
        - containerPort: 8000
        volumeMounts:
        - name: shm
          mountPath: /dev/shm
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 60
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 60
          periodSeconds: 5
