apiVersion: apps.nvidia.com/v1alpha1
kind: NIMPipeline
metadata:
  name: pipeline
spec:
  services:
   - name: nv-embedqa-e5-v5
     enabled: true
     spec:
      tolerations:
      - key: "nvidia.com/gpu"
        operator: "Exists"
        effect: "NoSchedule"
      image:
        repository: nvcr.io/nim/nvidia/llama-3.2-nv-embedqa-1b-v2
        tag: 1.3.1
        pullPolicy: IfNotPresent
        pullSecrets:
        - ngc-secret
      authSecret: ngc-api-secret
      storage:
        nimCache:
          name: nv-embedqa-e5-v5
          profile: ''
      replicas: 1
      resources:
        limits:
          nvidia.com/gpu: 1
      expose:
        service:
          type: ClusterIP
          port: 8000
   - name: nv-rerank-mistral-4b-v3
     enabled: true
     spec:
       tolerations:
       - key: "nvidia.com/gpu"
         operator: "Exists"
         effect: "NoSchedule"
       image:
         repository: nvcr.io/nim/nvidia/llama-3.2-nv-rerankqa-1b-v2
         tag: 1.3.1
         pullPolicy: IfNotPresent
         pullSecrets:
         - ngc-secret
       authSecret: ngc-api-secret
       storage:
         nimCache:
           name: nv-rerankqa-mistral-4b-v3
           profile: ''
       replicas: 1
       resources:
         limits:
           nvidia.com/gpu: 1
       expose:
         service:
           type: ClusterIP
           port: 8000
