apiVersion: v1
kind: ServiceAccount
metadata:
  name: thanos
---
apiVersion: v1
kind: Secret
metadata:
  name: thanos-token
  annotations:
    kubernetes.io/service-account.name: thanos 
type: kubernetes.io/service-account-token
